### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by nith229644** [Superbstingray/UdonPlayerPlatformHook#2]
![image](https://user-images.githubusercontent.com/16740744/163275729-8b49c122-edf7-4c42-b1b0-ea5d5f6b9e7f.png)
when I try to publish my world it happened like this every time. I also update Udonsharp and SDK to the lastest

**Comment by Superbstingray** [comment]
If you can post your world ID here so I can verify the issue and or message me on discord @ Superbstingray#6437 so I can look into this further I would appricate it!

**Comment by nith229644** [comment]
> 

I add you on Discord and my name is Jerker
wrld_ddb7dfa8-8a34-4135-8c32-50322fac28d3
