### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by AshTHP** [Superbstingray/UdonPlayerPlatformHook#3]
in the latest version of the VRchat SDK and Udon sharp gives me an error

![Capture](https://github.com/Superbstingray/UdonPlayerPlatformHook/assets/143916778/032bdc9a-e099-450f-84b1-733ad33470cf)

I have no clue how to fix this

is there a way for it to be fixed?

**Comment by Superbstingray** [comment]
That error will appear when there is no player controller. For example when you go to build and publish in the older SDK versions or try run in editor play mode without ClientSim active. The error doesn't cause any issues but I will still update the script to prevent it from showing.

**Comment by AshTHP** [comment]
alright thank you
