### ISSUE TITLE
Players in Half Body not working correctly

### ISSUE THREAD

**Issue by LlamahatStudio** [Superbstingray/UdonPlayerPlatformHook#5]
Seems that players with half body tracking (Head & Hands) will have their upper body translate correctly but their lower half will be frozen in place. This is rather funny but not good functionally, any idea why this could be an issue?

**Comment by Superbstingray** [comment]
If nothing has changed in recent VRC updates, this is still likely the intended behavior, as the script should lock the player's legs until they turn at least 90 degrees. This prevents the leg IK from dragging or appearing as if it's walking. You can disable the 'reduce IK drift' setting if you don't want the script to override the leg behavior.
